In [1]:
import matplotlib.pyplot as plt
import numpy as np
import scipy.spatial as sc
from scipy import stats
import seaborn as sns
sns.set_style("white")
import pandas as pd
import math as mt
from random import uniform
import random

#Data Generation (IRIS, Sepal length, Sepal Width)
data = [[5.1, 3.5], [4.9, 3], [4.7, 3.2], [4.6, 3.1], [5, 3.6], [5.4, 3.9], [4.6, 3.4], [5, 3.4], [4.4, 2.9], [4.9, 3.1]]
idx = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
df = pd.DataFrame(data, columns=['X', 'Y'], index=idx)

#Array, Variables
lrd = []
inpointidx = []
knnidx = []
LOF = []
lrdko = []
a = 0

#Euclidean distance matrix
distance = pd.DataFrame(sc.distance_matrix(df.values, df.values), index=df.index, columns=df.index)

#k-distance
for i in range(1,11):
    dis = np.array(distance[i])
    dis = np.delete(dis, [i-1])
    sortdis = np.array(distance[i])
    sortdis = np.delete(sortdis, [i-1])
    sortdis.sort()
    kdis = sortdis[2]

#N(k)p
    inpointidx1 = np.where(dis<=kdis)
    knnidx.append(inpointidx1)
    inpointidx = inpointidx1[0]
    nkp = np.size(inpointidx)

#Rechability distance
    for j in inpointidx:
        dis[j] = kdis

    lrdp = (nkp) / sum(dis[inpointidx])
    lrd.append(lrdp)


#LOF
for k in range(0, 10):
    nkpo = knnidx[k]
    for l in range(0, len(nkpo[0])):
        nkpoe = nkpo[0]
        a = a + lrd[nkpoe[l]]
    lrdko.append(a)
    a = 0

for t in range(0, 10):
    lof = (lrdko[t]/lrd[t]) / nkp
    LOF.append(lof)

print(LOF)

[1.1619346643522603, 1.0114624117730471, 0.59591471917943473, 0.91961512340540119, 0.93882142817315828, 1.4881150906711611, 1.3740625717777226, 0.67812907843971182, 1.8641585236851919, 1.0967746948501309]


In [2]:
#Data Generation (IRIS, Sepal length, Sepal Width)
data = [[5.1, 3.5], [4.9, 3], [4.7, 3.2], [4.6, 3.1], [5, 3.6], [5.4, 3.9], [4.6, 3.4], [5, 3.4], [4.4, 2.9], [4.9, 3.1]]
idx = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
df = pd.DataFrame(data, columns=['X', 'Y'], index=idx)

df

X    Y
1   5.1  3.5
2   4.9  3.0
3   4.7  3.2
4   4.6  3.1
5   5.0  3.6
6   5.4  3.9
7   4.6  3.4
8   5.0  3.4
9   4.4  2.9
10  4.9  3.1

In [3]:
#Euclidean distance matrix
distance = pd.DataFrame(sc.distance_matrix(df.values, df.values), index=df.index, columns=df.index)

distance

1         2         3         4         5         6         7   \
1   0.000000  0.538516  0.500000  0.640312  0.141421  0.500000  0.509902   
2   0.538516  0.000000  0.282843  0.316228  0.608276  1.029563  0.500000   
3   0.500000  0.282843  0.000000  0.141421  0.500000  0.989949  0.223607   
4   0.640312  0.316228  0.141421  0.000000  0.640312  1.131371  0.300000   
5   0.141421  0.608276  0.500000  0.640312  0.000000  0.500000  0.447214   
6   0.500000  1.029563  0.989949  1.131371  0.500000  0.000000  0.943398   
7   0.509902  0.500000  0.223607  0.300000  0.447214  0.943398  0.000000   
8   0.141421  0.412311  0.360555  0.500000  0.200000  0.640312  0.400000   
9   0.921954  0.509902  0.424264  0.282843  0.921954  1.414214  0.538516   
10  0.447214  0.100000  0.223607  0.300000  0.509902  0.943398  0.424264   

          8         9         10  
1   0.141421  0.921954  0.447214  
2   0.412311  0.509902  0.100000  
3   0.360555  0.424264  0.223607  
4   0.500000  0.282843  0.300000  
5   0.200000  0.921954  0.509902  
6   0.640312  1.414214  0.943398  
7   0.400000  0.538516  0.424264  
8   0.000000  0.781025  0.316228  
9   0.781025  0.000000  0.538516  
10  0.316228  0.538516  0.000000

In [4]:
#k-distance
for i in range(1,11):
    dis = np.array(distance[i])
    dis = np.delete(dis, [i-1])
    sortdis = np.array(distance[i])
    sortdis = np.delete(sortdis, [i-1])
    sortdis.sort()
    kdis = sortdis[2]

#N(k)p
    inpointidx1 = np.where(dis<=kdis)
    knnidx.append(inpointidx1)
    inpointidx = inpointidx1[0]
    nkp = np.size(inpointidx)

#Rechability distance
    for j in inpointidx:
        dis[j] = kdis

    lrdp = (nkp) / sum(dis[inpointidx])
    lrd.append(lrdp)
    
sortdis

array([ 0.1       ,  0.2236068 ,  0.3       ,  0.31622777,  0.42426407,
        0.4472136 ,  0.50990195,  0.53851648,  0.94339811])

In [6]:
kdis

0.30000000000000071

In [7]:
dis

array([ 0.4472136 ,  0.3       ,  0.3       ,  0.3       ,  0.50990195,
        0.94339811,  0.42426407,  0.31622777,  0.53851648])

In [8]:
knnidx

[(array([3, 6, 8], dtype=int64),),
 (array([1, 2, 8], dtype=int64),),
 (array([2, 5, 8], dtype=int64),),
 (array([2, 5, 7], dtype=int64),),
 (array([0, 5, 6], dtype=int64),),
 (array([0, 4, 6], dtype=int64),),
 (array([2, 3, 6], dtype=int64),),
 (array([0, 4, 8], dtype=int64),),
 (array([1, 2, 3], dtype=int64),),
 (array([1, 2, 3], dtype=int64),)]

In [9]:
nkp

3

In [10]:
lrd

[2.2360679774997916,
 3.162277660168372,
 4.4721359549995761,
 3.3333333333333353,
 2.236067977499788,
 1.5617376188860601,
 2.4999999999999978,
 3.1622776601683822,
 1.9611613513818404,
 3.3333333333333255]

In [11]:
#LOF
for k in range(0, 10):
    nkpo = knnidx[k]
    for l in range(0, len(nkpo[0])):
        nkpoe = nkpo[0]
        a = a + lrd[nkpoe[l]]
    lrdko.append(a)
    a = 0

for t in range(0, 10):
    lof = (lrdko[t]/lrd[t]) / nkp
    LOF.append(lof)

print(LOF)

LOF

[1.1619346643522603,
 1.0114624117730471,
 0.59591471917943473,
 0.91961512340540119,
 0.93882142817315828,
 1.4881150906711611,
 1.3740625717777226,
 0.67812907843971182,
 1.8641585236851919,
 1.0967746948501309]