In [10]:
import numpy as np
from scipy.sparse.linalg import eigsh

def LLE(X, n_neighbors, n_components):

    x_matrix = np.asmatrix(X).T
    D, N = x_matrix.shape

    sum_X = np.sum(np.square(X), 1)
    D = np.add(np.add(-2 * np.dot(X, X.T), sum_X).T, sum_X)
    distance = np.asmatrix(D)

    index=np.argsort(distance,axis=0)
    neighborhood = index[1:(n_neighbors+1),:]

    W = np.zeros((n_neighbors,N))
    tol = 1e-3


    # for variables
    for i in range(N):
        z = x_matrix[:, np.array(neighborhood[:,i]).reshape(-1)] - np.tile(x_matrix[:,i],(1,n_neighbors)) # shift ith pt to origi
        C = z.T*z # local covariance
        C = C + np.eye(n_neighbors) * tol * np.trace(C)
        I = np.ones((n_neighbors))
        W[:,i] = np.linalg.solve(np.array(C),I)
        W[:,i] = W[:,i]/sum(W[:,i])


    M = np.eye(N)  # M = (I-W)' (I-W)

    for i in range(N):
        w = W[:, i]
        j = neighborhood[:, i]
        M[i, j] = M[i, j] - np.asmatrix(w).T
        M[j, i] = M[j, i] - np.asmatrix(w).T
        M[j, j] = M[j, j] + np.asmatrix(w*w.T).T

    eigenvals, Y = eigsh(M, n_components + 1, tol=1e-3, sigma=0.0, maxiter = 100)

    return Y[:, 1:], np.sum(eigenvals[1:])




In [20]:
from sklearn import (datasets,random_projection)
from time import time
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import offsetbox
from LLE import LLE


digits = datasets.load_digits(n_class=6)
X = digits.data
y = digits.target
n_samples, n_features = X.shape
n_neighbors = 30

In [9]:
x_matrix = np.asmatrix(X).T
D, N = x_matrix.shape
print(D, N)

64 1083


In [13]:
x_matrix[:, np.array(neighborhood[:,0]).reshape(-1)]

matrix([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 7.,  5.,  5., ...,  3.,  3.,  6.],
        ..., 
        [ 3.,  1.,  2., ...,  3.,  9.,  5.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [22]:
np.tile(x_matrix[:,0],(1,n_neighbors))

matrix([[ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 5.,  5.,  5., ...,  5.,  5.,  5.],
        ..., 
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.],
        [ 0.,  0.,  0., ...,  0.,  0.,  0.]])

In [30]:
np.eye(6)

array([[ 1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.]])

In [34]:
W = np.zeros((n_neighbors,N))
tol = 0.001
for i in range(N):
    z = x_matrix[:, np.array(neighborhood[:,i]).reshape(-1)] - np.tile(x_matrix[:,i],(1,n_neighbors)) # shift ith pt to origi
    C = z.T*z # local covariance
    C = C + np.eye(n_neighbors) * tol * np.trace(C)
    I = np.ones((n_neighbors))
    W[:,i] = np.linalg.solve(np.array(C),I)
    W[:,i] = W[:,i]/sum(W[:,i])

In [36]:
 M = np.eye(N)  # M = (I-W)' (I-W)

In [40]:
i = 0

w = W[:, i]
len(w)

30

In [42]:
j = neighborhood[:, i]
len(j)

30

In [44]:
np.asmatrix(w).T
len(np.asmatrix(w).T)

30