In [157]:

import numpy as np
import cvxpy as cvx
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler


def linear_kernel(x1, x2):
    
    return np.dot(x1, x2)

def polynomial_kernel(x, y, p=3):
    
    return (1 + np.dot(x, y)) ** p

def gaussian_kernel(x, y, sigma=5.0):
    
    return np.exp(-np.linalg.norm(x-y)**2 / (2 * (sigma ** 2)))


class SVM(object):
    
    def __init__(self, kernel='linear', C=1.0):
        self.kernel = kernel
        self.C = C
    
        if self.C is not None:
            self.C = float(self.C)

    def _kernel_transform(self, X_train, kernel):
        if kernel == 'linear':
            kfunc = linear_kernel
        elif kernel == 'polynomial':
            kfunc = polynomial_kernel
        elif kernel == 'gaussian':
            kfunc = gaussian_kernel
            
        self.kfunc = kfunc
        
        n_samples, n_features = X_train.shape
        self.n_samples = n_samples 
        self.n_features = n_features 
    
        K = np.zeros((n_samples, n_samples))
        
        for i in range(n_samples):
            for j in range(n_samples):
                K[i,j] = kfunc(X_train[i], X_train[j])
             
        return K

    def __solve(self, K_matrix, y_train, C):
        
        n = y_train.shape[0] 
        y_= np.diag(y_train)  # 180 by 180(1 & -1) 
        alpha = cvx.Variable(n) 
        # constraints 
        constraints = []
        for i in range(n):
            constraints += [alpha[i] >= 0, alpha[i] <= C] 
        constraints += [y_train * alpha == 0]
        self.model_obj = cvx.Maximize(np.ones(n) * alpha - .5 * cvx.quad_form(alpha, y_.dot(K_matrix).dot(y_)))#convex식 
        #quad form 
        self.model = cvx.Problem(objective=self.model_obj, constraints=constraints)
        self.model.solve() 
        
        
        #support vector 
        self.a = np.array(alpha.value).flatten()
        self.sv = self.a > 1e-5 
        self.ind = np.arange(len(self.a))[self.sv] 
        self.a = self.a[self.sv] 
        self.sv_y = y_train[self.sv]
        self.sv_x= self.X_train[self.sv] 
        
        # intercept
        self.b = 0 
        for n in range(len(self.a)):
            self.b+=self.sv_y[n]
            self.b-=np.sum(self.a*self.sv_y*K_matrix[self.ind[n],self.sv])
        self.b/=len(self.a)
        
        #weight vector
        if self.kernel == 'linear':
            self.w = np.zeros(self.n_features)
            for n in range(len(self.a)):
                    self.w += self.a[n] * self.sv_y[n] * self.sv_x[n]
        else:
            self.w = None
            
    
    def predict(self,X):
        if self.w is not None:
           
            return np.dot(X,self.w) + self.b
          
        else: 
            y_predict = np.zeros(len(X))#
            
            for i in range(len(X)):
                s=0
                for a, sv_y, sv_x in zip(self.a, self.sv_y, self.sv_x):
                    s += a * sv_y * self.kfunc(X[i], sv_x)
                y_predict[i] = s
                
            return y_predict + self.b 
    def signpredict(self, X_test):
        
        return np.sign(self.predict(X_test))
    
    def fit(self, X_train, y_train):
        self.X_train = X_train 
        K = self._kernel_transform(X_train, self.kernel) 
        self.K = K
        self.__solve(K, y_train, self.C)


In [ ]:
def linear_kernel(x1, x2):
    
    return np.dot(x1, x2)

def polynomial_kernel(x, y, p=3):
    
    return (1 + np.dot(x, y)) ** p

def gaussian_kernel(x, y, sigma=5.0):
    
    return np.exp(-np.linalg.norm(x-y)**2 / (2 * (sigma ** 2)))


In [ ]:
model= SVM(kernel = 'gaussian', C=100.00)

In [108]:
    def gen_non_lin_separable_data():
        mean1 = [-1,2]
        mean2 = [1,-1]
        mean3 = [4,-4]
        mean4 = [-4,4]
        cov = [[1.0,0.8],[0.8,1.0]]
        
        X1 = np.random.multivariate_normal(mean1, cov, 50) 
        X1 = np.vstack((X1, np.random.multivariate_normal(mean3,cov,50)))
        y1 = np.ones(len(X1)) 
        X2 = np.random.multivariate_normal(mean2, cov, 50)
        X2 = np.vstack((X2,np.random.multivariate_normal(mean4,cov,50)))
        y2 = np.ones(len(X2))*-1
        
        return X1, y1, X2, y2

In [109]:
    def split_train(X1,y1,X2,y2): 
        scaler = StandardScaler()
        
        X1_train = X1[:90]
        y1_train = y1[:90]
        X2_train = X2[:90]
        y2_train = y2[:90]
        X_train = np.vstack((X1_train, X2_train))
        y_train = np.hstack((y1_train, y2_train))
        
        X1_test = X1[90:]
        y1_test = y1[90:]
        X2_test = X2[90:]
        y2_test = y2[90:]
        X_test = np.vstack((X1_test,X2_test))
        y_test = np.hstack((y1_test,y2_test))
        
        scaler.fit(X_train)
        X_train = scaler.transform(X_train)
        X_test = scaler.transform(X_test)

        return X_train, y_train, X_test, y_test 

In [110]:
X1,y1,X2,y2 = g.gen_non_lin_separable_data()
X_train, y_train, X_test, y_test = g.split_train(X1,y1,X2,y2)
print(X_train, y_train, X_test, y_test)

In [164]:
import generate as g
import svm_yooyeon as s

X1,y1,X2,y2 = g.gen_non_lin_separable_data()#
X_train, y_train, X_test, y_test = g.split_train(X1,y1,X2,y2)
print(X_train, y_train, X_test, y_test)
print("X_train:",len(X_train),"X_test:",len(X_test),"Y_train:",len(y_train),"Y_test:",len(y_test))

[[ 0.23534505  0.87616773]
 [-0.34242724  0.36097239]
 [-0.32023191  0.54442753]
 [-0.3093839   0.74927531]
 [-0.31245583  0.56082735]
 [-0.84716011  0.01893477]
 [-0.13615001  0.68903742]
 [-0.18045124  0.66593834]
 [-0.54547879  0.21639478]
 [-0.67247054  0.42910484]
 [ 0.03673463  1.08998039]
 [-0.04975031  1.05922865]
 [-0.30514542  0.36249528]
 [-0.22265914  0.77150158]
 [-0.53665024  0.13924504]
 [-0.17036832  0.5771982 ]
 [-0.46758167  0.88400961]
 [-0.01983986  0.96199463]
 [-0.24199913  0.58032978]
 [-0.59708597  0.31607705]
 [-0.38450569  0.29914693]
 [-0.8342253   0.15176668]
 [ 0.1905929   0.73887961]
 [-0.52996028  0.18379794]
 [-0.24877023  0.5962069 ]
 [-0.85210792  0.29369629]
 [-0.13438383  0.69309589]
 [-0.2291018   0.59048931]
 [-0.18523259  0.55039692]
 [-0.10784627  1.15905992]
 [-0.72071785  0.29809001]
 [-0.03576105  0.51249252]
 [-0.29573104  0.52658448]
 [-0.13350692  0.51090278]
 [-1.29327605 -0.033384  ]
 [-0.10082902  0.92461397]
 [-1.17643574  0.1105841 ]
 

In [111]:
model= SVM(kernel = 'gaussian', C=100.00)

In [112]:
model.fit(X_train, y_train)

In [ ]:
def fit(self, X_train, y_train):
        self.X_train = X_train 
        K = self._kernel_transform(X_train, self.kernel) 
        self.K = K
        self.__solve(K, y_train, self.C)

In [ ]:
def _kernel_transform(self, X_train, kernel):
        #choose Kernel 
        if kernel == 'linear':
            kfunc = linear_kernel
        elif kernel == 'polynomial':
            kfunc = polynomial_kernel
        elif kernel == 'gaussian':
            kfunc = gaussian_kernel
            
        self.kfunc = kfunc
        
        # Kernel Matrix
        #Number of observations and features in model(input:X_train)
        n_samples, n_features = X_train.shape
        self.n_samples = n_samples 
        self.n_features = n_features 
        
        K = np.zeros((n_samples, n_samples))
        
        for i in range(n_samples):
            for j in range(n_samples):
                K[i,j] = kfunc(X_train[i], X_train[j]) #(180*180)
             
        return K

In [73]:
from IPython.display import HTML, display
data=model.K #(180*180)
display(HTML(
    '<table><tr>{}</tr></table>'.format(
        '</tr><tr>'.join(
            '<td>{}</td>'.format('</td><td>'.join(str(_) for _ in row)) for row in table)
        )
 ))


In [ ]:
# use cvxpy to solve dual equation (convex optimization problem)
# cvxpy modeling: features, constraints, optimal equation
#               : alpha, w, b, support vectors(x & y)
def __solve(self, K_matrix, y_train, C):
      
    n = y_train.shape[0]  
    y_= np.diag(y_train) # 180 by 180(composed of 1 & -1)
    
    alpha = cvx.Variable(n)  

In [ ]:
# alpha constraints 
    constraints = []
        for i in range(n):
            constraints += [alpha[i] >= 0, alpha[i] <= C] 
        constraints += [y_train * alpha == 0]

In [155]:
from IPython.display import Math
Math(r's.t. \sum_{i=1}^na_iy_i = 0 \\and\\ 0<=a_i<=C')

<IPython.core.display.Math object>

In [ ]:
# model's optimal equation(dual function) and result 
        self.model_obj = cvx.Maximize(np.ones(n) * alpha - .5 * cvx.quad_form(alpha, y_.dot(K_matrix).dot(y_))) 
        self.model = cvx.Problem(objective=self.model_obj, constraints=constraints)
        self.model.solve() 

In [151]:
from IPython.display import Math
Math(r'max L_D = \sum_{i=1}^na_i - \frac{1}{2}\sum_{i=1}^n\sum_{j=1}^na_ia_jy_iy_jK(x_i,x_j)')

<IPython.core.display.Math object>

In [ ]:
 # alphas, support vectors 
        # 2-dimension -> 1-dimension
        self.a = np.array(alpha.value).flatten()
        # constraint: a > 0
        self.sv = self.a > 1e-5  
        self.ind = np.arange(len(self.a))[self.sv] 
        self.a = self.a[self.sv] 
        self.sv_y = y_train[self.sv]
        self.sv_x= self.X_train[self.sv]  

In [124]:
# alphas
print('- alphas of the model:\n', model.a)

- Alphas of the model:
 [ 30.67474583  67.04244931  99.99999933  99.99999966  38.11494161
  99.99999977  89.98887345   2.25385489  99.99999954  99.99999995
  99.99999979  11.11141436  59.05428111  98.22005097  59.68912001]


In [158]:
# support vector's x values
print('- support vector x values of the model:\n',model.sv_x)
len(model.sv_x)

- support vector x values of the model:
 [[ 0.47089355  1.24642284]
 [-0.29107762  0.32581831]
 [-0.52134448  0.05990857]
 [-0.47978544  0.08773656]
 [-1.14885474  0.26873144]
 [ 0.11349822  0.72630892]
 [ 1.28090293 -1.03127924]
 [ 0.84583706 -1.58578819]
 [ 0.22976561 -0.16153275]
 [-0.13220388 -0.41185441]
 [ 0.58786124  0.16589611]
 [ 0.71592853  0.21609775]
 [ 0.1753085  -0.23112449]
 [-1.43251518  0.68665797]
 [-0.46578659  1.63957133]]


15

In [159]:
# support vector's y values
print('- support vector y values of the model:\n',model.sv_y)
len(model.sv_y)

- support vector y values of the model:
 [ 1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1.]


15

In [ ]:
# intercept of the model
        self.b = 0 
        for n in range(len(self.a)):
            self.b+=self.sv_y[n]
            self.b-=np.sum(self.a*self.sv_y*K_matrix[self.ind[n],self.sv])
        self.b/=len(self.a)

In [144]:
from IPython.display import Math
Math(r'b = y_i-\sum_{i=1}^n(a_iy_iK(x_i,x_j))')


<IPython.core.display.Math object>

In [156]:
# intercept of the model
print('- intercept of the model:\n',model.b)

- intercepts of the model:
 -0.954319717866


In [ ]:
# weight vector of the model
        if self.kernel == 'linear':
            self.w = np.zeros(self.n_features)
            for n in range(len(self.a)):
                    self.w += self.a[n] * self.sv_y[n] * self.sv_x[n]
        else:
            self.w = None

In [167]:
from IPython.display import Math
Math(r' w = \sum_{i=1}^n(a_iy_ix_i)')

<IPython.core.display.Math object>

In [125]:
# weight vector of the model 
print('- Weight vectors of the model:\n',model.w)

- Weights of the model:
 None


In [ ]:
#predicted y from model
def predict(self,X):  
        if self.w is not None:
                   # wxT+b
            return np.dot(X,self.w) + self.b 
          
        else: 
            y_predict = np.zeros(len(X))   
            
            for i in range(len(X)):
                s=0
                for a, sv_y, sv_x in zip(self.a, self.sv_y, self.sv_x):
                    s += a * sv_y * self.kfunc(X[i], sv_x)  
                y_predict[i] = s
                   # w*kernel(x)+b
            return y_predict + self.b  

In [143]:
from IPython.display import Math
Math(r' w = \sum_{i=1}^n(a_iy_iK(x_i,x_j))')

<IPython.core.display.Math object>

In [131]:
# predicted y values of X_test
print('- Predicted y values of X_test:\n',model.predict(X_test))#( 754 * 2)


- Predicted y values of X_test:
 [ 4.4581406   2.91256616  2.04083023  2.38156581  2.63746601  4.98712059
  1.39395896  3.24610909  3.81727459  2.02541259 -4.94432892 -4.10344383
 -3.9002355  -5.17518492 -3.49016431 -4.88104101 -4.26143758 -2.3984097
 -3.82748458 -2.0740838 ]


In [ ]:
def signpredict(self, X_test):
                # signs of y_test
        return np.sign(self.predict(X_test))
    

In [145]:
from IPython.display import Math
Math(r'f(x) = sign(y_i-\sum_{i=1}^n(a_iy_iK(x_i,x_j))')

<IPython.core.display.Math object>

In [134]:
# predicted signs of y values of X_test 
y_predict = model.signpredict(X_test) 
print('- Predicted signs of y values of X_test:\n',y_predict)

- Predicted signs of y values of X_test:
 [ 1.  1.  1.  1.  1.  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1.
 -1. -1.]


In [135]:
correct = np.sum(y_predict == y_test)
print("%d out of %d predictions correct" % (correct, len(y_predict)))

20 out of 20 predictions correct
